module.exports = {
  fic:[
    {
      Timestamp: "4/21/2021 13:57:45",
      Email: "",
      Name: "Prof. Mahesh Chandra Govil",
      Email: "",
      Role: "Patron",
      Instagram: "",
      Linkedin: "https://www.linkedin.com/in/mahesh-govil-0275271a6",
      Facebook: "",
      Description: "",
      photo: "/assets/images/image/dr.mahesh.png"
    },
    {
      Timestamp: "4/21/2021 13:57:45",
      Email: "",
      Name: "Dr. Hemant K. Kathania",
      Email: "",
      Role: "Faculty in-charge",
      Instagram: "",
      Linkedin: "https://www.linkedin.com/in/hemant-kathania-71583947/",
      Facebook: "https://www.facebook.com/hemant.kathaniaiitguwahati",
      Description: "",
      photo: "/assets/images/image/dr.hemant.jpg"
    },
],
  advisories: [
    {
      Timestamp: "4/21/2021 13:57:45",
      Email: "b170091@nitsikkim.ac.in",
      Name: "Deepak Choudhary",
      Email: "b170091@nitsikkim.ac.in",
      Role: "Advisory Committee",
      Instagram: "",
      Linkedin: "https://www.linkedin.com/in/deepak-choudhary-23728b170",
      Facebook: "https://www.facebook.com/deepakthegod07",
      Description: "",
      photo: "/assets/images/image/Deepak choudhary.png"
    },
    {
      Timestamp: "4/21/2021 13:57:45",
      Email: "b170062@nitsikkim.ac.in",
      Name: "Prashant Gupta",
      Email: "b170062@nitsikkim.ac.in",
      Role: "Advisory Committee",
      Instagram: "https://www.instagram.com/prashantlfh?r=nametag",
      Linkedin: "https://www.linkedin.com/in/prashant-gupta-364548170",
      Facebook: "",
      Description: "",
      photo: "/assets/images/image/prashant.jpg"
    },
    {
      Timestamp: "4/20/2021 15:47:30",
      Email: "b170030@nitsikkim.ac.in",
      Name: "Ankita Singh",
      Email: "b170030@nitsikkim.ac.in",
      Role: "Advisory Committee",
      Instagram: "",
      Linkedin: "https://www.linkedin.com/in/ankita-singh-80a70b178",
      Facebook: "",
      Description: "Final Year ECE Undergraduate,Did Summer internship at C-DAC Chennai,Interest area: VLSI design",
      photo: "/assets/images/image/ankita.png"
    },
    {
      Timestamp: "4/20/2021 14:05:20",
      Email: "b170087@nitsikkim.ac.in",
      Name: "Girija Nandan Kar",
      Email: "b170087@nitsikkim.ac.in",
      Role: "Advisory Committee",
      Instagram: "",
      Linkedin: "https://www.linkedin.com/in/girijanandankar",
      Facebook: "",
      Description: "",
      photo: "/assets/images/image/girija.jpg"
    },
    {
      Timestamp: "4/20/2021 14:05:20",
      Email: "",
      Name: "Durgesh Gupta",
      Email: "",
      Role: "Advisory Committee",
      Instagram: "",
      Linkedin: "https://www.linkedin.com/in/durgesh-gupta-a75b25186",
      Facebook: "",
      Description: "",
      photo: "/assets/images/image/durgesh gupta.jpg"
    }
  ],
  volunteers: [{
      Timestamp: "4/20/2021 23:25:18",
      Email: "b190068@nitsikkim.ac.in",
      Name: "Srishti Prasad",
      Email: "b190068@nitsikkim.ac.in",
      Role: "Volunteer",
      Instagram: "https://instagram.com/__srishti_26?igshid=6t7v8nie7hb2",
      Linkedin: "https://www.linkedin.com/in/srishti-prasad-436581209",
      Facebook: "https://www.facebook.com/srishti.prasad.90",
      Description: "I regard myself to be very optimistic, determined, focused and responsible person.",
      photo: "/assets/images/image/srishti.png"
    },

    {
      Timestamp: "4/20/2021 14:01:10",
      Email: "B190043@nitsikkim.ac.in",
      Name: "Prashu Kumar Sharma",
      Email: "b190043@nitsikkim.ac.in",
      Role: "Volunteer",
      Instagram: "https://www.instagram.com/_prashu.sharma_/",
      Linkedin: "https://www.linkedin.com/in/prashu-kumar-sharma-10679020b/",
      Facebook: "https://www.facebook.com/pk.raj.756",
      Description: "I’m organized. I really enjoy working with a wide variety of people to achieve a common goal efficiently and realistically.",
      photo: "/assets/images/image/Prashu.png"
    },
    {
      Timestamp: "4/21/2021 14:33:33",
      Email: "b200094@nitsikkim.ac.in",
      Name: "Anirudh Ghildiyal",
      Email: "b200094@nitsikkim.ac.in",
      Role: "Volunteer",
      Instagram: "",
      Linkedin: "https://www.linkedin.com/in/anirudh-ghildiyal-19338520a/",
      Facebook: "",
      Description: "",
      photo: "/assets/images/image/Anirudh"
    },
    {
      Timestamp: "4/20/2021 14:32:11",
      Email: "b190061@nitsikkim.ac.in",
      Name: "Raunak Singh",
      Email: "b190061@nitsikkim.ac.in",
      Role: "Volunteer",
      Instagram: "https://www.instagram.com/rau_nak_/",
      Linkedin: "https://linkedin.com/in/raunak-singh-91b4891b1/",
      Facebook: "I don't have Facebook ID.",
      Description: "An architect of life who builds its foundation and choose its contents, a simple mind with a versatile nature and just a student who wants to touch the heights of innovation and technology.",
      photo: "/assets/images/image/Raunak.png"
    },
    {
      Timestamp: "4/20/2021 17:41:10",
      Email: "b200098@nitsikkim.ac.in",
      Name: "Sakshee Rajpoot",
      Email: "b200098@nitsikkim.ac.in",
      Role: "Volunteer",
      Instagram: "",
      Linkedin: "https://www.linkedin.com/in/sakshee-rajpoot-0593b0197",
      Facebook: "",
      Description: "",
      photo: "/assets/images/image/Sakshee.png"
    },
    {
      Timestamp: "4/21/2021 10:25:53",
      Email: "b200084@nitsikkim.ac.in",
      Name: "Riya Mathur",
      Email: "b200084@nitsikkim.ac.in",
      Role: "Volunteer",
      Instagram: "https://www.instagram.com/riiyamathur/",
      Linkedin: "https://www.linkedin.com/in/riya-mathur-2827ba1ba",
      Facebook: "",
      Description: "",
      photo: "/assets/images/image/Riya.png"
    },
    {
      Timestamp: "4/21/2021 11:55:53",
      Email: "b190044@nitsikkim.ac.in",
      Name: "Vanka Janaki Rama Santhosh",
      Email: "b190044@nitsikkim.ac.in",
      Role: "Volunteer",
      Instagram: "https://www.instagram.com/santhosh_chowdary_vanka?r=nametag",
      Linkedin: "https://www.linkedin.com/in/janaki-rama-santhosh-vanka-6aba4719a",
      Facebook: "",
      Description: "Think Practically",
      photo: "/assets/images/image/VankiJanaRamaSantosh.png"
    },
    {
      Timestamp: "4/21/2021 12:10:34",
      Email: "b200089@nitsikkim.ac.in",
      Name: "Adarsh Kumar",
      Email: "b200089@nitsikkim.ac.in",
      Role: "Volunteer",
      Instagram: "",
      Linkedin: "https://www.linkedin.com/in/adarsh-kumar-896a2920a",
      Facebook: "",
      Description: "",
      photo: "/assets/images/image/Adarsh.jpg"
    },
    {
      Timestamp: "4/20/2021 14:01:10",
      Email: "b200076@nitsikkim.ac.in",
      Name: "Siddharth Utsav",
      Email: "b200076@nitsikkim.ac.in",
      Role: "Volunteer",
      Instagram: "https://instagram.com/_siddharth_uk_37_?igshid=1fs6icfeuzrv4",
      Linkedin: "https://www.linkedin.com/in/siddharth-utsav-karna-53a3691a6",
      Facebook: "https://www.facebook.com/profile.php?id=100005532588384",
      Description: "I’m organized. I really enjoy working with a wide variety of people to achieve a common goal efficiently and realistically.",
      photo: "/assets/images/image/Siddhart Utsav.png"
    },
  ],
  coordinators: [{
      Timestamp: "4/21/2021 14:52:37",
      Email: "b180093@nitsikkim.ac.in",
      Name: "Khushbu Gupta",
      Email: "b180093@nitsikkim.ac.in",
      Role: "Social Media Lead",
      Instagram: "",
      Linkedin: "https://www.linkedin.com/in/khushbu-gupta-a324581a7",
      Facebook: "https://www.facebook.com/profile.php?id=100025378697732",
      Description: "",
      photo: "/assets/images/image/Khushbu gupta.png"
    },
    {
      Timestamp: "4/21/2021 15:00:30",
      Email: "b180087@nitsikkim.ac.in",
      Name: "Ashwini Saikiran",
      Email: "b180087@nitsikkim.ac.in",
      Role: "Resource Management Lead",
      Instagram: "",
      Linkedin: "https://www.linkedin.com/in/ashwini-saikiran-94a218192",
      Facebook: "",
      Description: "",
      photo: "/assets/images/image/Ashwini saikiran.png"
    },
    {
      Timestamp: "4/21/2021 17:45:44",
      Email: "b180066@nitsikkim.ac.in",
      Name: "Mididodla Jaswanth Sai",
      Email: "b180066@nitsikkim.ac.in",
      Role: "Editorial Lead",
      Instagram: "https://www.instagram.com/jaswanthsai0909/",
      Linkedin: "https://www.linkedin.com/in/jaswanth-sai-mididodla-8229b6172/",
      Facebook: "https://www.facebook.com/jaswanthsai.mididodla",
      Description: "",
      photo: "/assets/images/image/jas.png"
    },
    {
      Timestamp: "4/21/2021 14:00:38",
      Email: "b180090@nitsikkim.ac.in",
      Name: "Sanjeev Kumar Sharma",
      Email: "sanjeevkumar9823@gmail.com",
      Role: "Resource Management Lead",
      Instagram: "https://www.instagram.com/sanjeevshrmaa/",
      Linkedin: "https://www.linkedin.com/in/sanjeevshrmaa/",
      Description: " It is not enough that I should succeed -- others should fail ",
      photo: "/assets/images/image/Sanjeev kumar.png"
    },
    {
      Timestamp: "4/21/2021 12:42:02",
      Email: "b180079@nitsikkim.ac.in",
      Name: "Deepak Gupta",
      Email: "b180079@nitsikkim.ac.in",
      Role: "Technical Lead",
      Instagram: "",
      Github: "https://github.com/deepakgupta191199",
      Linkedin: "https://linkedin.com/in/deepakgupta191199",
      Facebook: "",
      Description: "",
      photo: "/assets/images/image/Deepak gupta.png"
    },
    {
      Timestamp: "4/21/2021 12:42:02",
      Email: "b180074@nitsikkim.ac.in",
      Name: "Prashant Prasad",
      Email: "b180074@nitsikkim.ac.in",
      Role: "Social Media Lead",
      Instagram: "",
      Linkedin: "https://www.linkedin.com/in/prashant-prasad-367217192",
      Facebook: "",
      Description: "",
      photo: "/assets/images/image/prasant.jpeg"
    },
    {
      Timestamp: "4/21/2021 10:22:35",
      Email: "b180081@nitsikkim.ac.in",
      Name: "Shagir Husain",
      Email: "b180081@nitsikkim.ac.in",
      Role: "Technical Lead",
      Instagram: "",
      Linkedin: "https://www.linkedin.com/in/shagir-husain-19a4911a4",
      Facebook: "",
      Description: "",
      photo: "/assets/images/image/Shagir.jpg"
    },
    {
      Timestamp: "4/20/2021 19:51:00",
      Email: "b190045@nitsikkim.ac.in",
      Name: "Aanchal Soni",
      Email: "b190045@nitsikkim.ac.in",
      Role: "Editorial Lead",
      Instagram: "https://www.instagram.com/aanchalsoni_12_10/",
      Linkedin: "https://www.linkedin.com/in/aanchal-soni-a1a305201",
      Facebook: "https://m.facebook.com/aanchal.soni.1422?ref=bookmarks",
      Description: "An intentive, a perceptive, and a collaborative member. Proactive she, instates as the Editorial Team Co-ordinator of the club.",
      photo: "/assets/images/image/Aanchal.png"
    },
  ],

  head: [{
    Timestamp: "4/20/2021 19:05:20",
    Email: "b180099@nitsikkim.ac.in",
    Name: "Anjali Roy",
    Email: "b180099@nitsikkim.ac.in",
    Role: "Convener",
    Instagram: "",
    Linkedin: "https://www.linkedin.com/in/anjali-roy-2ab2a616b",
    Facebook: "",
    Description: "",
    photo: "/assets/images/image/Anjali Roy1.jpg"
  },
  {
    Timestamp: "4/21/2021 13:50:22",
    Email: "b180094@nitsikkim.ac.in",
    Name: "Abadhesh kumar",
    Email: "b180094@nitsikkim.ac.in",
    Role: "Treasurer",
    Instagram: "",
    Linkedin: "",
    Facebook: "",
    Description: "",
    photo: "/assets/images/image/abadesh.png"
  },
   {
    Timestamp: "4/21/2021 13:50:22",
    Email: "b180091@nitsikkim.ac.in",
    Name: "Gourav Kumar Prasad",
    Email: "b180091@nitsikkim.ac.in",
    Role: "Secretary",
    Instagram: "https://www.instagram.com/_gourav3/",
    Linkedin: "https://www.linkedin.com/in/gourav-kumar-prasad-263095168/",
    Facebook: "https://www.facebook.com/gauravkdk/",
    Description: "",
    photo: "/assets/images/image/Gourav.png"
  },
],
}
